max_exceeded: silent
mode: queued
max: 20

blueprint:
  domain: automation
  name: Entity State Save and Restore
  description: Restores the state of an entity when it becomes unavailable or unknown. Allows optional restoration of attributes.
  source_url: https://github.com/selfish/home-assistant-resources/blob/master/config/blueprints/entity_state_restore.yaml

  # depends_on: 
  #   - https://github.com/PiotrMachowski/Home-Assistant-custom-components-Saver
  #   - https://github.com/selfish/home-assistant-resources/blob/master/config/python_scripts/set_state.py 

  input:
    entity:
      name: Entity
      description: The entities to monitor
      selector:
        entity:

variables:
  entity: !input entity

trigger:
  - id: state_change
    platform: state
    entity_id: !input entity
  - id: ha_restart
    platform: homeassistant
    event: start
    

action:
  - if:
      - condition: trigger
        id: state_change
      - condition: not
        conditions:
          - condition: state
            entity_id: !input entity
            state:
              - "unavailable"
              - "unknown"
    then:
      service: saver.save_state
      data:
        entity_id: !input entity
    else:
      - service: python_script.set_state
        data:
          entity_id: !input entity
          state: "{{ saver_entity(entity) }}"
